Update README.md
cds-snc/gcds-docs pull request #215
Opened 2023-09-21 17:25 UTC by daine

# Summary | Résumé

Updates the readme with the URL where the pages are accessible

2023-09-21 18:43 UTC, melaniebmn commented on README.md
> +- [FR] The site will be accesible on http://localhost:8080/en or http://localhost:8080/fr. You have to append the `/en` and `/fr` as there is no page available at the base url
Can you get this translated by Amy or Anik so that this whole section stays in French? You could also try the `traduction-gcds` channel.

2023-09-21 18:43 UTC, melaniebmn requested changes
Thanks for adding this in! The PR is good to go once we get the sentence translated :)

2023-09-25 14:38 UTC, anikbrazeau commented on README.md
> +- The site will be accesible on http://localhost:8080/en or http://localhost:8080/fr. You have to append the `/en` and `/fr` as there is no page available at the base url
```suggestion
- The site will be accessible on http://localhost:8080/en or http://localhost:8080/fr. You have to append the `/en` and `/fr` as there is no page available at the base url
```

2023-09-25 14:38 UTC, anikbrazeau commented on README.md
> +- [FR] The site will be accesible on http://localhost:8080/en or http://localhost:8080/fr. You have to append the `/en` and `/fr` as there is no page available at the base url
```suggestion
- Le site sera accessible sur http://localhost:8080/fr or http://localhost:8080/en. Vous devrez ajouter `/fr` ou `/en` en suffixe car il n'y a pas de page disponible à l'URL de base.
```

2023-09-25 15:58 UTC, melaniebmn approved these changes
LGTM

2023-09-25 16:20 UTC, merged