About us content update
cds-snc/gcds-docs pull request #254
Opened 2023-12-08 14:52 UTC by ethanWallace

# Summary | Résumé

Update contact us page to separate the about us content into it's own page. Also changed `foundations` pages to be `styles` and all the navigation changes that required.

2023-12-08 21:24 UTC, daine approved these changes
LGTM

2023-12-12 22:17 UTC, melaniebmn requested changes
One small question, otherwise looks great!

2023-12-13 18:11 UTC, ethanWallace commented on src/en/installation.md
> +Changes to GC Design System (GCDS-) come in a single version update with tokens, components, and (usually) non-breaking changes. GC Design System is independent of the Web Experience Toolkit (WET) an
Good catch

2023-12-18 16:58 UTC, melaniebmn approved these changes
LGTM

2024-01-03 20:51 UTC, daine approved these changes
Looks good!

2024-01-04 13:39 UTC, merged