Update accessibility.md
cds-snc/gcds-docs pull request #427
Opened 2024-10-01 04:16 UTC by adorayi

Added draft EN content (for presentation), will probably be refined further once I get comments from Amy. Matilde's comments have been applied.

Not sure about the link to contact us page though at the bottom of the page, it's not on the same level.

# Summary | Résumé

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.

---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

2025-02-03 19:29 UTC, ethanWallace commented
It's looking good!

I do find the statuses (completed, in progress, etc) kind of get lost in each line. Are we able to add some additional formatting to them?

2025-02-03 19:50 UTC, adorayi commented
Thanks, I will look into the formatting for the next update.

2025-02-04 15:51 UTC, ethanWallace requested changes
Since the accessibility page is now being handled in another pull request , can we remove it from this pull request?

Can we also update the title and description of this pull request to accurately describe the changes of this pull request?

2025-02-04 19:18 UTC, ethanWallace approved these changes
LGTM

2025-02-04 19:25 UTC, merged