Chnage site file structure for new release
cds-snc/gcds-docs pull request #61
Opened 2023-01-13 21:10 UTC by ethanWallace

# Summary | Résumé

Multiple changes to help with upcoming release

## New file structure

Component pages are now made up from multiple files. See example below:
```
  - component-name
    - component-name.md (shared block of text that is rendered on each page)
    - use-case.md (components/component-name/)
    - design.md (components/component-name/design/)
    - code.md (components/component-name/code/)
```

## Blank component files

Created blank component files for each component in the design system. Did not carry over the content from previous version. Some modifications still need to be done, like hiding the page if we don't have the documentation yet.

## New create-documentation-page script

Running `npm run create-documentation-page` will create english and french pages for a new component. The script will prompt asking for the `english name` and `french name`. Each name should be written as it displays in a url. See example below:

```
> npm run create-component-page
> English name?: breadcrumbs
> French name?: fil-dariane
```

2023-01-17 18:25 UTC, melaniebmn commented on src/fr/composants/fil-dariane/case-dusage.md
> +title: fil-dariane - Composants
Nick recommended using `Chemin de navigation` as the french translation for `Breadcrumbs` instead of `Fil d\'Ariane`.

2023-01-17 18:30 UTC, melaniebmn commented on src/fr/composants/fil-dariane/code.md
> +title: fil-dariane - Composants
Same comment.

2023-01-17 18:30 UTC, melaniebmn commented on src/fr/composants/fil-dariane/design.md
> +title: fil-dariane - Composants
Same comment.

2023-01-17 18:31 UTC, melaniebmn commented on src/fr/composants/fil-dariane/fil-dariane.md
> +# fil-dariane
Same comment.

2023-01-17 19:07 UTC, melaniebmn requested changes
Nice, thanks for updating the structure!

2 comments for potentially renaming files:
- Instead of using `component-name/component-name.md`, how about giving that file a dedicated name as well so that it can be named consistently for all components? Maybe something like `component-name/base.md`.
- Right now we are using `token-documentation.njk` and `documentation.njk`. The token-documentation is used for foundation pages in general. How about renaming it to`foundation-documentation.njk` and renaming  `documentation.njk` to `component-documentation.njk` to clearly show that it is supposed to be used for documenting components?

2023-01-17 22:21 UTC, ethanWallace commented
@melaniebmn 

>Instead of using component-name/component-name.md, how about giving that file a dedicated name as well so that it can be named consistently for all components? Maybe something like component-name/base.md.

Great idea! Made the change.

> Right now we are using token-documentation.njk and documentation.njk. The token-documentation is used for foundation pages in general. How about renaming it tofoundation-documentation.njk and renaming documentation.njk to component-documentation.njk to clearly show that it is supposed to be used for documenting components?

I do like this idea. I changed the documentation to component-documentation. We might rename the `foundations` section of the site to `tokens` so I am going to leave that layout alone.

2023-01-18 00:56 UTC, melaniebmn commented on src/fr/composants/base.md
> +---
Looks like this file is a duplicate of `src/fr/composants/Case-a-cocher/base.md` - was that intentional?

2023-01-18 00:57 UTC, melaniebmn commented on src/fr/composants/case-dusage.md
> +---
Same comment here, looks like this was supposed to be part of the checkbox folder.

2023-01-18 00:57 UTC, melaniebmn commented on src/fr/composants/code.md
> +---
And same comment here, looks like this was supposed to be part of the checkbox folder.

2023-01-18 00:58 UTC, melaniebmn commented on src/fr/composants/design.md
> +---
And last one - looks like this was supposed to be part of the checkbox folder.

2023-01-18 01:04 UTC, melaniebmn requested changes
Looks like the french checkbox files went a little haywire, but otherwise, it looks good.

2023-01-18 01:05 UTC, melaniebmn commented
> @melaniebmn
> 
> > Instead of using component-name/component-name.md, how about giving that file a dedicated name as well so that it can be named consistently for all components? Maybe something like component-name/base.md.
> 
> Great idea! Made the change.
> 
> > Right now we are using token-documentation.njk and documentation.njk. The token-documentation is used for foundation pages in general. How about renaming it tofoundation-documentation.njk and renaming documentation.njk to component-documentation.njk to clearly show that it is supposed to be used for documenting components?
> 
> I do like this idea. I changed the documentation to component-documentation. We might rename the `foundations` section of the site to `tokens` so I am going to leave that layout alone.

Ok awesome, I didn't know we were potentially changing it to 'tokens' so yeah, let's stick with that for now,

2023-01-18 16:47 UTC, melaniebmn approved these changes
LGTM

2023-01-18 18:32 UTC, merged